{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Operation", "query": "label_values(operation)\t" }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(rate(span_duration_bucket{operation=\"$Operation\"}[5m]))",
     "legendFormat": "Rate"
    },
    {
     "expr": "sum(rate(general_traces{operation=\"$Operation\", error=\"true\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Error",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(general_traces{operation=\"$Operation\", error=\"true\"}[5m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(span_duration_bucket{operation=\"$Operation\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}